// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qd9-ULz2xYaVx4CX_0L1i8nQmhnGB7k',
    appId: '1:727905531405:web:5d5439c700ab3df92fc744',
    messagingSenderId: '727905531405',
    projectId: 'edupro-45bb5',
    authDomain: 'edupro-45bb5.firebaseapp.com',
    databaseURL: 'https://edupro-45bb5-default-rtdb.firebaseio.com',
    storageBucket: 'edupro-45bb5.appspot.com',
    measurementId: 'G-LQ2REXM0KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq50hLcg97qlXvaU-R1CuZDOGaR0onJhQ',
    appId: '1:727905531405:android:abdab548d4be5de72fc744',
    messagingSenderId: '727905531405',
    projectId: 'edupro-45bb5',
    databaseURL: 'https://edupro-45bb5-default-rtdb.firebaseio.com',
    storageBucket: 'edupro-45bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflZC3nyik37bTFabowyAkSeGW4DF4cJ4',
    appId: '1:727905531405:ios:c6e5eb84bb027c222fc744',
    messagingSenderId: '727905531405',
    projectId: 'edupro-45bb5',
    databaseURL: 'https://edupro-45bb5-default-rtdb.firebaseio.com',
    storageBucket: 'edupro-45bb5.appspot.com',
    iosBundleId: 'com.example.edupro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCflZC3nyik37bTFabowyAkSeGW4DF4cJ4',
    appId: '1:727905531405:ios:c6e5eb84bb027c222fc744',
    messagingSenderId: '727905531405',
    projectId: 'edupro-45bb5',
    databaseURL: 'https://edupro-45bb5-default-rtdb.firebaseio.com',
    storageBucket: 'edupro-45bb5.appspot.com',
    iosBundleId: 'com.example.edupro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qd9-ULz2xYaVx4CX_0L1i8nQmhnGB7k',
    appId: '1:727905531405:web:432156b621fa55a62fc744',
    messagingSenderId: '727905531405',
    projectId: 'edupro-45bb5',
    authDomain: 'edupro-45bb5.firebaseapp.com',
    databaseURL: 'https://edupro-45bb5-default-rtdb.firebaseio.com',
    storageBucket: 'edupro-45bb5.appspot.com',
    measurementId: 'G-7KKE191X8L',
  );

}